// Obligaciones v11: flujo mensual, pensión en UTM y reajuste tributario UF básico.
(function(){
const OSTORE='obligaciones_v11';
const UTM={
 '2025-01':67294,'2025-02':67294,'2025-03':68470,'2025-04':68897,'2025-05':68915,'2025-06':68648,'2025-07':68647,'2025-08':68647,'2025-09':69120,'2025-10':69265,'2025-11':69265,'2025-12':69265,
 '2026-01':69265,'2026-02':69265,'2026-03':70326,'2026-04':70588,'2026-05':70588,'2026-06':71506,'2026-07':71506,'2026-08':71506,'2026-09':71506,'2026-10':71506,'2026-11':71506,'2026-12':71506
};
const UF={
 '2025-01':38416,'2025-02':38430,'2025-03':38609,'2025-04':38894,'2025-05':39106,'2025-06':39267,'2025-07':39376,'2025-08':39485,'2025-09':39625,'2025-10':39765,'2025-11':39880,'2025-12':40000,
 '2026-01':40120,'2026-02':40260,'2026-03':40420,'2026-04':40580,'2026-05':40740,'2026-06':40900,'2026-07':41050,'2026-08':41200,'2026-09':41350,'2026-10':41500,'2026-11':41650,'2026-12':41800
};
function q(id){return document.getElementById(id)}
function clp(v){if(window.clp)return window.clp(v);let n=Number(String(v||'').replace(/\D/g,''));return n||0}
function money(n){return '$'+Math.round(+n||0).toLocaleString('es-CL')}
function ym(d){return String(d||'').slice(0,7)}
function y(d){return +String(d||'').slice(0,4)||new Date().getFullYear()}
function loadO(){try{return JSON.parse(localStorage.getItem(OSTORE))||seed()}catch(e){return seed()}}
function saveO(){localStorage.setItem(OSTORE,JSON.stringify(OB));renderObl();}
function seed(){return{items:[{id:'obl_pension',name:'Pensión alimentos',type:'pension',currency:'UTM',amount:21.1108,dueDay:5,active:true}],payments:[]}}
let OB=loadO();
function inject(){
 if(q('sObl'))return;
 const sec=document.createElement('section');sec.id='sObl';sec.innerHTML=`
 <div class="card"><div class="k">Flujo mensual y obligaciones</div><p class="note">Registra arriendo, deudas, gastos fijos y pensión. La pensión queda en UTM y se calcula con la UTM del mes correspondiente.</p><div class="row"><div><label>Mes</label><input type="month" id="oblMonth"></div><div><label>Ingreso líquido caja</label><input id="oblIncome" placeholder="opcional"></div><div style="align-self:end"><button class="btn" onclick="renderObl()">Actualizar</button></div><div style="align-self:end"><button class="btn btn2" onclick="seedPension()">Crear/actualizar pensión 21,1108 UTM</button></div></div></div>
 <div class="grid card"><div><div class="k">Obligaciones mes</div><div class="v mono" id="oDue">$0</div></div><div><div class="k">Pagado</div><div class="v mono good" id="oPaid">$0</div></div><div><div class="k">Pendiente</div><div class="v mono bad" id="oPending">$0</div></div><div><div class="k">Flujo libre</div><div class="v mono" id="oFree">$0</div></div></div>
 <div class="card"><div class="k">Agregar obligación</div><div class="row"><div><label>Nombre</label><input id="obName" placeholder="Arriendo, crédito, tarjeta"></div><div><label>Tipo</label><select id="obType"><option value="pension">Pensión</option><option value="arriendo">Arriendo</option><option value="deuda">Deuda</option><option value="tarjeta">Tarjeta</option><option value="fijo">Gasto fijo</option><option value="otro">Otro</option></select></div><div><label>Moneda</label><select id="obCurrency"><option>CLP</option><option>UF</option><option>UTM</option></select></div><div><label>Monto</label><input id="obAmount" placeholder="21,1108 o 500000"></div></div><button class="btn btnG" onclick="addObligation()">Guardar obligación</button></div>
 <div class="card"><div class="k">Pagar obligación</div><div class="row"><div><label>Obligación</label><select id="payObl"></select></div><div><label>Mes asociado</label><input type="month" id="payMonth"></div><div><label>Monto pagado</label><input id="payAmount" placeholder="vacío = cálculo automático"></div><div><label>Nota</label><input id="payNote"></div></div><button class="btn btnG" onclick="payObligation()">Guardar pago</button></div>
 <div class="card"><div class="k">Detalle obligaciones</div><div id="oblTable" class="scroll"></div></div>
 <div class="card"><div class="k">Reajuste tributario UF preliminar</div><p class="note">Convierte cada base tributable real a UF del mes de pago y la reexpresa a la UF de cierre seleccionada. Ajusta la UF de cierre AT según el dato oficial que quieras usar.</p><div class="row"><div><label>Año tributario</label><input id="ufTaxYear" type="number" placeholder="2026"></div><div><label>UF cierre AT</label><input id="ufClose" placeholder="Ej: 40000"></div><div style="align-self:end"><button class="btn btn2" onclick="calcUfTax()">Calcular reajuste</button></div><div><label>Diferencia residual</label><div class="v mono" id="ufDiff">$0</div></div></div><div id="ufTaxTbl" class="scroll"></div></div>`;
 document.body.insertBefore(sec,document.querySelector('nav'));
 const nav=document.querySelector('nav'); const b=document.createElement('button'); b.dataset.t='sObl'; b.textContent='Flujo'; b.onclick=()=>window.nav?window.nav('sObl'):null; nav.insertBefore(b,nav.children[3]||null);
 let m=new Date().toISOString().slice(0,7); q('oblMonth').value=m; q('payMonth').value=m; q('ufTaxYear').value=new Date().getFullYear(); renderObl();
}
function unitValue(cur,month){if(cur==='UTM')return UTM[month]||0;if(cur==='UF')return UF[month]||0;return 1}
function dueAmount(o,month){return Math.round(Number(o.amount||0)*unitValue(o.currency,month))}
window.seedPension=function(){let p=OB.items.find(x=>x.id==='obl_pension'); if(!p){OB.items.push({id:'obl_pension',name:'Pensión alimentos',type:'pension',currency:'UTM',amount:21.1108,dueDay:5,active:true})}else{p.amount=21.1108;p.currency='UTM';p.active=true;} saveO();}
window.addObligation=function(){let name=q('obName').value||'Obligación';OB.items.push({id:'o'+Date.now(),name,type:q('obType').value,currency:q('obCurrency').value,amount:Number(String(q('obAmount').value).replace(',','.'))||0,dueDay:5,active:true});saveO();}
window.payObligation=function(){let id=q('payObl').value, month=q('payMonth').value, o=OB.items.find(x=>x.id===id); if(!o)return; let amt=clp(q('payAmount').value)||dueAmount(o,month);OB.payments.push({id:'p'+Date.now(),obligationId:id,month,amount:amt,note:q('payNote').value||''});saveO();}
window.renderObl=function(){if(!q('sObl'))return;let month=q('oblMonth').value||new Date().toISOString().slice(0,7);let income=clp(q('oblIncome').value)||((window.S?.records||[]).filter(r=>ym(r.paymentDate)===month).reduce((s,r)=>s+clp(r.netClp),0));let rows=OB.items.filter(o=>o.active!==false).map(o=>{let due=dueAmount(o,month), paid=OB.payments.filter(p=>p.obligationId===o.id&&p.month===month).reduce((s,p)=>s+clp(p.amount),0);return{...o,due,paid,pending:due-paid,unit:unitValue(o.currency,month)}});let due=rows.reduce((s,o)=>s+o.due,0),paid=rows.reduce((s,o)=>s+o.paid,0);q('oDue').textContent=money(due);q('oPaid').textContent=money(paid);q('oPending').textContent=money(due-paid);q('oFree').textContent=money(income-due);q('payObl').innerHTML=OB.items.map(o=>`<option value="${o.id}">${o.name}</option>`).join('');q('oblTable').innerHTML='<table><tr><th>Obligación</th><th>Moneda</th><th>Monto base</th><th>Valor mes</th><th>Debe</th><th>Pagado</th><th>Pendiente</th></tr>'+rows.map(o=>`<tr><td>${o.name}<br><span class="note">${o.type}</span></td><td>${o.currency}</td><td>${o.amount}</td><td>${o.currency==='CLP'?'—':money(o.unit)}</td><td class="money">${money(o.due)}</td><td class="money">${money(o.paid)}</td><td class="money">${money(o.pending)}</td></tr>`).join('')+'</table>';}
window.calcUfTax=function(){let ty=Number(q('ufTaxYear').value)||new Date().getFullYear(), close=Number(String(q('ufClose').value).replace(',','.'))||UF[String(ty-1)+'-12']||0;let rec=(window.S?.records||[]).filter(r=>(window.isRealTaxableRecord?window.isRealTaxableRecord(r):r.isTaxable!==false)&&Number(r.taxYear)===ty);let rows=rec.map(r=>{let m=ym(r.paymentDate), u=Number(r.ufValue)||UF[m]||0, base=clp(r.taxableBaseClp), tax=clp(r.withheldTaxClp), adj=u&&close?Math.round(base/u*close):base, adjTax=u&&close?Math.round(tax/u*close):tax;return{r,m,u,base,tax,adj,adjTax}});let baseAdj=rows.reduce((s,x)=>s+x.adj,0), taxAdj=rows.reduce((s,x)=>s+x.adjTax,0);let renta=(window.S?.rentas||[]).find(r=>Number(r.taxYear)===ty), diff=renta?baseAdj-clp(renta.baseF22):0;q('ufDiff').textContent=money(diff);q('ufTaxTbl').innerHTML='<p class="note">Base reajustada: <b>'+money(baseAdj)+'</b> · Impuesto reajustado: <b>'+money(taxAdj)+'</b>'+ (renta?' · Base F22: <b>'+money(renta.baseF22)+'</b>':'')+'</p><table><tr><th>Fecha</th><th>Detalle</th><th>UF mes</th><th>Base nominal</th><th>Base reaj.</th><th>Imp. reaj.</th></tr>'+rows.map(x=>`<tr><td>${x.r.paymentDate}</td><td>${x.r.description||''}</td><td>${x.u||'—'}</td><td>${money(x.base)}</td><td>${money(x.adj)}</td><td>${money(x.adjTax)}</td></tr>`).join('')+'</table>';}
setTimeout(inject,300);
})();